# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataStoringPractise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
pod 'Alamofire'

  # Pods for DataStoringPractise

  target 'DataStoringPractiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataStoringPractiseUITests' do
    # Pods for testing
  end

end
