# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DataBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'

  # Pods for DataBase

  target 'DataBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataBaseUITests' do
    # Pods for testing
  end

end
